name: LifeMC
version: 2.4.1
main: pw.nebula.universe.LifeMC
softdepend: [Vault, PlaceholderAPI]
authors: [Staartvin, Bluemond, JohnDelisle]
api-version: 1.15
commands:
  lifemc:
    description: Main command of LifeMC.
    usage: /lifemc <arguments>
    aliases: [lives, life]
permissions:
  lifemc.lives.give:
    description: Can give lives to other players.
    default: true
  lifemc.lives.gain:
    description: Can gain lives by eating certain items.
    default: true
  lifemc.lives.check:
    description: Can use /lives to see their own lives.
    default: true
  lifemc.lives.check.other:
    description: Can use /lives <player> to see anyones lives.
    default: op
  lifemc.lives.set:
    description: Can use /lives set <player> <amount> to edit anyones lives.
    default: op
    children:
      lifemc.lives.add: true
      lifemc.lives.remove: true
  lifemc.lives.add:
    description: Can use /lives add <player> <amount> to edit anyones lives.
    default: op
  lifemc.lives.remove:
    description: Can use /lives remove <player> <amount> to edit anyones lives.
    default: op
  lifemc.lives.buy:
    description: Can use /lives buy <amount> to buy lives with iConomy
    default: true
  lifemc.lives.lose:
    description: Can lose a life on death.
    default: true
  lifemc.murder:
    description: Can gain life on murder
    default: op
  lifemc.revive:
    description: Revive player by giving them a life
    default: true
  lifemc.*:
    description: Access to all lifemc commands
    default: op
    children:
      lifemc.lives.give: true
      lifemc.lives.gain: true
      lifemc.lives.check: true
      lifemc.lives.check.other: true
      lifemc.lives.set: true
      lifemc.lives.add: true
      lifemc.lives.remove: true
      lifemc.lives.buy: true
      lifemc.lives.lose: true
      lifemc.murder: true
      lifemc.revive: true
