name: LifeMC
version: 2
main: me.bluemond.lifemc.LifeMC
commands:
  lives:
    description: Returns the amount of lives you have.
    usage: /lives OR /lives <playerName> OR /lives <set/add/remove> <playerName> <amount> OR /lives buy <amount> OR /lives cost
  permissions:
  lifemc.*:
    description: Access to all LifeMC permission nodes.
    default: false
    children:
      lifemc.givelives: true
      lifemc.eatdiamonds: true
      lifemc.seeownlives: true
      lifemc.revive: true
      lifemc.seeotherslives: true
      lifemc.livesediting: true
      lifemc.livesbuying: true
      lifemc.ondeathloselife: true
  lifemc.givelives:
    description: Can give lives to other players.
    default: true
  lifemc.eatdiamonds:
    description: Can eat diamonds to gain lives.
    default: true
  lifemc.seeownlives:
    description: Can use /lives to see their own lives.
    default: true
  lifemc.seeotherslives:
    description: Can use /lives <player> to see anyones lives.
    default: op
  lifemc.livesediting:
    description: Can use /lives <set/add/remove> <player> <amount> to edit anyones lives.
    default: op
  lifemc.livesbuying:
    description: Can use /lives buy <amount> to buy lives with iConomy
    default: true
  lifemc.revive:
    description: Can revive other players by giving lives.
    default: true
  lifemc.ondeathloselife:
    description: Can lose a life on death.
    default: true