name: LifeMC
version: 2.1
main: me.bluemond.lifemc.LifeMC
softdepend: [Vault]
authors: [Staartvin, Bluemond]
commands:
  lifemc:
    description: Main command of LifeMC.
    usage: /lifemc <arguments>
    aliases: [lives, life]
permissions:
  lifemc.lives.give:
    description: Can give lives to other players.
    default: true
  lifemc.lives.gain:
    description: Can gain lives by eating certain items.
    default: true
  lifemc.lives.check:
    description: Can use /lives to see their own lives.
    default: true
  lifemc.lives.check.other:
    description: Can use /lives <player> to see anyones lives.
    default: op
  lifemc.lives.set:
    description: Can use /lives set <player> <amount> to edit anyones lives.
    default: op
  lifemc.lives.add:
    description: Can use /lives add <player> <amount> to edit anyones lives.
    default: op
  lifemc.lives.remove:
    description: Can use /lives remove <player> <amount> to edit anyones lives.
    default: op
  lifemc.lives.buy:
    description: Can use /lives buy <amount> to buy lives with iConomy
    default: true
  lifemc.revive:
    description: Can revive other players by giving lives.
    default: true
  lifemc.lives.lose:
    description: Can lose a life on death.
    default: true